#ifndef IGLUI_WUI_H_DEFINED
#define IGLUI_WUI_H_DEFINED

#define TERRAIN_COLORS 35
#define TERRAIN_VERT 34
#define WUI_CLOSE 99
#define SAVE_SETTINGS_WUI 98
#define TERRAIN_TYPE 36
#define TERRAIN_MIN 37
#define TERRAIN_MAX 38
#define TERRAIN_FIRE_LINE_UPDATE 39

#endif

