#ifndef IGLUI_SMOKE_H_DEFINED
#define IGLUI_SMOKE_H_DEFINED

#define SCRIPT_CANCEL_NOW 45

#define FIRE_RED 1
#define FIRE_GREEN 2
#define FIRE_BLUE 3
#define SMOKE_RED 51
#define SMOKE_GREEN 52
#define SMOKE_BLUE 53
#ifndef UPDATE_SMOKEFIRE_COLORS
#define UPDATE_SMOKEFIRE_COLORS 54
#endif
#define UPDATE_SMOKEFIRE_COLORS2 61
#define UPDATE_SMOKEFIRE_COLORS_COMMON 62
#define CO2SMOKE 63
#define UPDATE_SMOKECOLORS 4
#define GLOBAL_FIRE_CUTOFF 15
#define SMOKE_SHADE 7
#define SMOKE_COLORBAR_LIST 16
#define FIRECOLORMAP_TYPE 17
#define CO2_COLORBAR_LIST 82
#define CO2COLORMAP_TYPE 83
#define SHOW_FIRECOLORMAP 25
#ifdef pp_GPU
#define SMOKE_RTHICK 8
#else
#define SMOKE_THICK 8
#endif
#define SAVE_SETTINGS_SMOKE 9
#define FRAMELOADING_SMOKE 10
#define SMOKETEST 11
#define VOL_SMOKE 13
#define VOL_NGRID 18
#define SMOKE_OPTIONS 19
#define LOAD_COMPRESSED_DATA 20
#define TEMP_MIN 21
#define TEMP_CUTOFF 22
#define TEMP_MAX 23
#define COMBINE_MESHES 24
#define MASS_EXTINCTION 85
#define NONGPU_VOL_FACTOR 26
#define GPU_VOL_FACTOR 27
#define GENERATE_IMAGES 28
#define START_FRAME 29
#define SKIP_FRAME 30
#define CANCEL_GENERATE_IMAGES 31
#define VOL_TOUR_LIST 46
#define VOL_PREFIX 47
#define VOL_UNLOAD_ALL 48
#define LIGHT_XYZ 49
#define LIGHT_UPDATE 50
#define LOAD_SMOKEFRAME 55
#define LOAD_TIMEFRAME 58
#define UPDATE_FACTOROFFSETS 59
#define UPDATE_HRRPUV_CONTROLS 60
#define SMOKE3D_LOAD_INCREMENTAL 18
#define CO2_COLOR 71
#define UPDATE_FIRE_ALPHA 72
#define UPDATE_CO2_ALPHA 73
#define SMOKE_SKIP 74
#define SMOKE_BLACK 75
#define SMOKE_DELTA_PAR 76
#define SMOKE_NEW 77
#define SMOKE_DELTA_MULTIPLE 78
#define SMOKEBOX_BUFFER 79
#define SMOKE_NUM 80
#define BACKGROUND_FLIP 81
#define USE_FIRE_ALPHA 84


#endif

