#ifndef IOSCRIPTS_H_DEFINED
#define IOSCRIPTS_H_DEFINED

#define EXTERNAL_VIEW 1

#define SCRIPT_RENDERONCE        101
#define SCRIPT_RENDERHTMLONCE    102
#define SCRIPT_RENDERHTMLALL     105
#define SCRIPT_RENDERHTMLDIR     109
#define SCRIPT_RENDERHTMLGEOM    123
#define SCRIPT_RENDERHTMLOBST    124
#define SCRIPT_RENDERHTMLSLICENODE 125
#define SCRIPT_RENDERHTMLSLICECELL 126
#define SCRIPT_RENDERDOUBLEONCE  103
#define SCRIPT_RENDERALL         104
#define SCRIPT_RENDER360ALL      106
#define SCRIPT_VOLSMOKERENDERALL 107
#define SCRIPT_RENDERDIR         108
#define SCRIPT_RENDERCLIP        110
#define SCRIPT_SCENECLIP         111
#define SCRIPT_XSCENECLIP        112
#define SCRIPT_YSCENECLIP        113
#define SCRIPT_ZSCENECLIP        114
#define SCRIPT_CBARFLIP          115
#define SCRIPT_CBARNORMAL        116
#define SCRIPT_RENDERSTART       117
#define SCRIPT_MAKEMOVIE         118
#define SCRIPT_RENDERTYPE        119
#define SCRIPT_RENDERSIZE        120
#define SCRIPT_MOVIETYPE         121
#define SCRIPT_ISORENDERALL      122

#define SCRIPT_LOADFILE          201
#define SCRIPT_LOADVFILE         202
#define SCRIPT_LOADBOUNDARY      203
#define SCRIPT_LOAD3DSMOKE       204
#define SCRIPT_LOADISO           205
#define SCRIPT_LOADPARTICLES     206
#define SCRIPT_LOADSLICE         207
#define SCRIPT_LOADVSLICE        208
#define SCRIPT_LOADTOUR          209
#define SCRIPT_UNLOADTOUR        210
#define SCRIPT_PARTCLASSCOLOR    211
#define SCRIPT_PARTCLASSTYPE     212
#define SCRIPT_LOADINIFILE       213
#define SCRIPT_LOADPLOT3D        214
#define SCRIPT_SHOWPLOT3DDATA    215
#define SCRIPT_PLOT3DPROPS       216
#define SCRIPT_LOADVOLSMOKE      217
#define SCRIPT_LOADVOLSMOKEFRAME 218
#define SCRIPT_LOADISOM          219
#define SCRIPT_LOADBOUNDARYM     220
#define SCRIPT_LOADSLICEM        221
#define SCRIPT_LOADVSLICEM       222
#define SCRIPT_SHOWSMOKESENSORS  223
#define SCRIPT_SMOKEFRAMES       224
#define SCRIPT_RGBTEST           225
#define SCRIPT_XYZVIEW           226
#define SCRIPT_VIEWXMIN          227
#define SCRIPT_VIEWXMAX          228
#define SCRIPT_VIEWYMIN          229
#define SCRIPT_VIEWYMAX          230
#define SCRIPT_VIEWZMIN          231
#define SCRIPT_VIEWZMAX          232
#define SCRIPT_LOADSLICERENDER   233
#define SCRIPT_LOADSLCF          234

#define SCRIPT_SETTIMEVAL        301
#define SCRIPT_SETVIEWPOINT      302
#define SCRIPT_UNLOADALL         303
#define SCRIPT_KEYBOARD          304
#define SCRIPT_GSLICEVIEW        305
#define SCRIPT_GSLICEPOS         306
#define SCRIPT_GSLICEORIEN       307
#define SCRIPT_SETTOURVIEW       308
#define SCRIPT_SETTOURKEYFRAME   309
#define SCRIPT_EXIT              310
#define SCRIPT_LABEL             311
#define SCRIPT_PROJECTION        312
#define SCRIPT_SETSLICEBOUNDS    314
#define SCRIPT_SETBOUNDBOUNDS    315

#define SCRIPT_SLICE_FILE          0
#define SCRIPT_BOUNDARY_FILE       1
#define SCRIPT_SMOKE3D_FILE        2
#define SCRIPT_PART_FILE           3
#define SCRIPT_ISO_FILE            4

#define SCRIPT_UNKNOWN            -1

#endif

