PROGRAM FDS

! Fire Dynamics Simulator, Main Program, Multiple CPU version.

USE PRECISION_PARAMETERS
USE COMPLEX_GEOMETRY, ONLY: TRIANGULATE, VALID_TRIANGLE

IMPLICIT NONE

INTEGER :: I

! Miscellaneous declarations
!SUBROUTINE TRIANGULATE(VERTS,NVERTS,VERT_OFFSET,FACES)
!  INTEGER, INTENT(IN) :: NVERTS, VERT_OFFSET
!  REAL(FB), INTENT(IN) :: VERTS(3*NVERTS)
!  INTEGER, INTENT(OUT) :: FACES(3*(NVERTS-2))

INTEGER :: NVERTS
REAL(FB) :: VERTS(300)
INTEGER :: VERT_OFFSET
INTEGER :: FACES(300)
LOGICAL :: TRITEST
INTEGER :: IV1, IV2, IV3

VERT_OFFSET=0
NVERTS=6

VERTS(1:18) = (/3.0,1.0,0.0, 2.0,1.0,0.0, 2.0,0.0,0.0, 0.0,0.0,0.0, 0.0,2.0,0.0, 3.0,2.0,0.0  /)


do i = 1, nverts - 2
IV1 = i
IV2 = i+1
IV3 = i+2
TRITEST = VALID_TRIANGLE(3,VERTS, NVERTS, IV1, IV2, IV3)
end do

CALL TRIANGULATE(3,VERTS,NVERTS,VERT_OFFSET,FACES)
do i = 1, nverts - 2
   write(0,*)"FACE",i,faces(3*i-2),faces(3*i-1),faces(3*I)
end do
write(0,*)"complete"

END PROGRAM FDS
